### ISSUE TITLE
Participants in group chat are unable to use Aiden

### ISSUE THREAD

**Issue by edawine** [laymonage/AidenBot#5]
The participants in the group chat are unable to use Aiden, if they are not friends yet with Aiden.
Is this a bug? Thanks.

**Comment by laymonage** [comment]
I'm not really sure about this, but it seems that it's because bots can't read chat messages from someone who hasn't accepted the agreement with the bot's provider (me). If I recall correctly, LINE shows a dialog box about this the first time someone adds a bot from a new provider, prompting them to either Agree or Disagree.

**Comment by edawine** [comment]
No, I don't have that box pop up for me or my friends. It's unexpected because a bot like "Kerang Ajaib" was able to operate just fine, without having to first add the bot ("Kerang Ajaib" is gone now, so this is about 2 months ago).

**Comment by laymonage** [comment]
You're right. It seems that the dialog box doesn't always appear. It does appear on LINE Lite and PC LINE, though.

I've been aware of this issue but I wasn't sure why, and I've nailed the problem just now. It turns out that the get_profile method only works if the user has added Aiden. If the user hasn't added him, different methods (get_group_member_profile and get_room_member_profile) need to be used.

I've pushed a commit that fixes this. Can you please test it again? Thanks!

**Comment by edawine** [comment]
Ok, my friends have confirmed the fix. Thanks.
